server:
  port: 8083
  servlet:
    context-path: /work-item-command-service

spring:
  application:
    name: work-item-command-service
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/workitems_db
    username: myuser
    password: mypassword
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin123
